### ISSUE TITLE
evidently checks always pass

### ISSUE THREAD

**Issue by charlesfrye** [zenml-io/zenml-gitflow#28]
this is only in the `devweek-demo` branch, where deepchecks was replaced with evidently

see this for little block of code, where `check_passed` is defined as true and then appended to `results` without checking the actual output

https://github.com/zenml-io/zenml-gitflow/blob/948df96aab9b7401f92c748755b353447ae18eb5/steps/model_appraisers.py#L163-L168

noticed it when i shuffled the labels in `train` to try and trigger the drift detector -- was hoping to demo that feature. the evidently report shows drift but the markdown report does not.

**Comment by stefannica** [comment]
Hey @charlesfrye , thanks for noticing. This should be fixed now in the branch.
